package e_bebek.cartTest.tests;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
//created by selenium
//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class Test2 {

	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Before
	public void setUp() throws MalformedURLException {
		System.setProperty("chromeDriver","drivers/chromedriver");
		driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), null);
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void ebebekSepet() throws InterruptedException {
		// Test name: e-bebek.com
		// Step # | name | target | value
		// 1 | open | / |
		driver.get("https://www.e-bebek.com/");
		driver.manage().window().setSize(new Dimension(914, 854));
		Thread.sleep(2000);
		// 3 | click | css=.ins-close-button-c2703 |
		driver.findElement(By.cssSelector(".ins-close-button-c2703")).click();
		driver.findElement(By.cssSelector(".search-wrapper")).click();
		driver.findElement(By.id("txtSearchBox")).sendKeys("kaşık maması");
		driver.findElement(By.id("txtSearchBox")).sendKeys(Keys.ENTER);
		Thread.sleep(2000);
		js.executeScript("window.scrollTo(0,1010.4000244140625)");
		js.executeScript("window.scrollTo(0,1868.800048828125)");
		js.executeScript("window.scrollTo(0,2456)");
		js.executeScript("window.scrollTo(0,2986.39990234375)");
		js.executeScript("window.scrollTo(0,4030.39990234375)");
		js.executeScript("window.scrollTo(0,6580.7998046875)");
		Thread.sleep(2000);
		driver.findElement(By.cssSelector(".col-6:nth-child(32) .product-item-anchor > .product-item-anchor")).click();
		driver.findElement(By.cssSelector(".col-6:nth-child(32) #addToCartBtn")).click();
		Thread.sleep(2000);
		// 15 | runScript | window.scrollTo(0,2324.800048828125) |
		js.executeScript("window.scrollTo(0,2324.800048828125)");
		// 16 | click | id=btnShowCart | added cart
		driver.findElement(By.id("btnShowCart")).click();
		js.executeScript("window.scrollTo(0,9.600000381469727)");
		Thread.sleep(2000);
		{
			WebElement element = driver.findElement(By.cssSelector(".cx-link > h2"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		// 19 | mouseOut | css=.cx-link > h2 |
		{
			WebElement element = driver.findElement(By.tagName("body"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element, 0, 0).perform();
		}
		// 20 | runScript | window.scrollTo(0,38.400001525878906) |
		js.executeScript("window.scrollTo(0,38.400001525878906)");
		// 21 | click | css=#btnGoToShippingAddress > .ng-star-inserted |
		driver.findElement(By.cssSelector("#btnGoToShippingAddress > .ng-star-inserted")).click();
		// 22 | runScript | window.scrollTo(0,515.2000122070312) |
		js.executeScript("window.scrollTo(0,515.2000122070312)");
		// 23 | close | |
		driver.close();
		{
			WebElement element = driver
					.findElement(By.cssSelector(".col-6:nth-child(3) .product-item-anchor .product-item-content"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		js.executeScript("window.scrollTo(0,214.39999389648438)");
		js.executeScript("window.scrollTo(0,256)");
		driver.findElement(By.cssSelector(".cx-item-list-row:nth-child(1) .dec-product")).click();
		driver.findElement(By.cssSelector(".cx-item-list-row:nth-child(1) .dec-product")).click();
		driver.findElement(By.id("btnGoToShippingAddress")).click();
		{
			WebElement element = driver.findElement(By.cssSelector(".btn-add-fav"));
			Actions builder = new Actions(driver);
			builder.moveToElement(element).perform();
		}
		js.executeScript("window.scrollTo(0,401.6000061035156)");
	}

	public static void main(String[] args) throws MalformedURLException, InterruptedException {

		Test2 t2 = new Test2();

		t2.setUp();
		t2.ebebekSepet();
		t2.tearDown();
	}

}
